/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigProvider: typeof import('./src/components/common/ConfigProvider.vue')['default']
    LBadgeText: typeof import('./src/components/ui/LBadgeText.vue')['default']
    LButton: typeof import('./src/components/ui/LButton.vue')['default']
    LCard: typeof import('./src/components/ui/LCard.vue')['default']
    LKeyboard: typeof import('./src/components/ui/LKeyboard.vue')['default']
    LogPanel: typeof import('./src/components/common/LogPanel.vue')['default']
    LTooltip: typeof import('./src/components/ui/LTooltip.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VotingPanel: typeof import('./src/components/common/voting-panel/VotingPanel.vue')['default']
    VotingType1: typeof import('./src/components/common/voting-panel/voting-type-1/VotingType1.vue')['default']
    VotingType2: typeof import('./src/components/common/voting-panel/voting-type-2/VotingType2.vue')['default']
    VT2Button: typeof import('./src/components/common/voting-panel/voting-type-2/VT2Button.vue')['default']
    VT2LCD: typeof import('./src/components/common/voting-panel/voting-type-2/VT2LCD.vue')['default']
    VT2LED: typeof import('./src/components/common/voting-panel/voting-type-2/VT2LED.vue')['default']
    VT2ScreenItem: typeof import('./src/components/common/voting-panel/voting-type-2/VT2ScreenItem.vue')['default']
  }
}
