/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigProvider: typeof import('./src/components/common/ConfigProvider.vue')['default']
    LBadgeText: typeof import('./src/components/ui/LBadgeText.vue')['default']
    LButton: typeof import('./src/components/ui/LButton.vue')['default']
    LCard: typeof import('./src/components/ui/LCard.vue')['default']
    LCD: typeof import('./src/components/common/VotePanel/LCD.vue')['default']
    LKeyboard: typeof import('./src/components/ui/LKeyboard.vue')['default']
    LogPanel: typeof import('./src/components/common/LogPanel.vue')['default']
    LTooltip: typeof import('./src/components/ui/LTooltip.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenItem: typeof import('./src/components/common/VotingMachine/ScreenItem.vue')['default']
    VotePanel: typeof import('./src/components/common/VotePanel/VotePanel.vue')['default']
    VotingMachine: typeof import('./src/components/common/VotingMachine/VotingMachine.vue')['default']
  }
}
