/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigProvider: typeof import('./src/components/common/ConfigProvider.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    LBadgeText: typeof import('./src/components/ui/LBadgeText.vue')['default']
    LButton: typeof import('./src/components/ui/LButton.vue')['default']
    LogPanel: typeof import('./src/components/common/LogPanel.vue')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    SettingDialog: typeof import('./src/components/common/SettingDialog.vue')['default']
    VoteBar: typeof import('./src/components/common/VoteBar.vue')['default']
    VotePanel: typeof import('./src/components/common/VotePanel.vue')['default']
  }
}
